# Generated by Django 4.2.1 on 2023-05-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contactinfo',
        ),
    ]
